---
title: "Exploring Patterns of Basic Needs in College Students "
output: 
  html_document: 
    toc: no
    css: styles.css
editor_options: 
  chunk_output_type: console
---

### Pilot #2: 402 EOP students at Fresno State, Chico State, and CSU, Northridge

Food insecurity among college students is a serious problem that can impact student performance in the classroom and ultimately effect student success. The [Center for Healthy Communities](https://www.csuchico.edu/chc/) (CHC) developed the **Basic Needs Student Success Survey (BNS3)** and administered it to undergraduate students participating in the [Educational Opportunity Program (EOP)](https://www2.calstate.edu/attend/student-services/eop) at [Chico State](https://www.csuchico.edu/eop/), [Fresno State](https://www.fresnostate.edu/studentaffairs/eop/abouteop.html) and [CSU, Northridge](https://www.csun.edu/csun-eop) from November 25$^{th}$, 2020 to March 24$^{th}$, 2021. The EOP offices assisted in the recruitment by emailing students a link to an interest form where eligibility criteria to take the survey was assessed *(being 18 years or older, undergraduate juniors/seniors, and being enrolled in the EOP)*. Participants were given a \$25 gift card for their participation. EOP students were identified as the target population for this survey based upon their low-income and first-generation student status, which indicates a higher probability of CalFresh eligibility.

The purpose of this second cross-sectional pilot study was to revise the BNS3 tool and validate student perception of the following:  

1. The impact of receiving [CalFresh](https://www.csuchico.edu/calfresh/index.shtml) assistance.
2. The impact of utilization of the campus food pantry on their health, nutrition, cooking
confidence, time management and academic performance. 

This report provides a top level descriptive analysis of each question in the survey. Researchers and campus staff are encouraged to review the information in this analysis to formulate additional research questions and hypotheses.

**Disclaimer on Missing Data:** Students were allowed to select answers such as "Prefer not to answer" or "I don't know" as responses to every question asked. These answers were then converted to missing values, denoted as *NA*, and this is the cause of the missing data for certain questions (not 100% of respondents reporting). The total number of non-missing responses (and percentage of the total data) are provided for each question. 

<br />


### [`r emo::ji("magnifying_glass_tilted_right")` How to use this website](Instructions.html)
*Click above for instructions on how to navigate the website and interpret graphs.*

<br />

### How to Cite This Website
Center for Healthy Communities. (2021). Pilot 2 Basic Needs and Student Success Survey. https://doi.org/10.5281/zenodo.12763019

<br />

### Related Works

* [Pilot 1 Basic Needs and Student Success Survey](https://chicocalfresh.github.io/BNS-Pilot1-website/)
* [Pilot 2 Basic Needs and Student Success Survey, CSU Chico Results](https://chicocalfresh.github.io/bns-pilot2-chico/)
* [Pilot 2 Basic Needs and Student Success Survey, CSU Northridge Results](https://chicocalfresh.github.io/bns-pilot2-csun/)
* [Pilot 2 Basic Needs and Student Success Survey, Fresno State Results](https://chicocalfresh.github.io/bns-pilot2-fresno/)
* [Statewide Basic Needs and Student Success Survey](https://chicocalfresh.github.io/BNS3_Statewide_Summary/)
* [Publication in the Journal of Hunger & Environmental Nutrition: Differences in Cooking Behavior and Infrastructure by Food Security Status Among Historically Underserved College Students](https://www.tandfonline.com/doi/epdf/10.1080/19320248.2024.2442943?needAccess=true)







